name: Create a GitHub release

on:
  push:
    branches:
      - main
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Test
      - name: Perform unit tests.
        run: |
          swift package resolve
          swift build
          swift test
      - name: Tests integrations from examples.
        run: ./scripts/test.sh
      # Release
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          # Relevant Branches
          release_branches: main
          pre_release_branches: next
          # Tag configuration
          tag_prefix: ''
          default_bump: false
          # Credentials
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: SwiftGraphQL ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
